### ISSUE TITLE
Usability: Upload Wizard

### ISSUE THREAD

**Issue by jdittrich** [BauhausUniversity/MedienWiki#10]
**Usecase:** _Marie wants to put an image of her work on a wikipage. She has a few pictures of it on her harddisk in .jpg format._

Uploading and using images is a problem 
- for users, since they find the local/wiki-Filename difference confusing and forget how to use the uploaded data
- for Admins, since it needs to be dealt with copyright infringements. 

The solution I currently favour is the [upload Wizard](https://www.mediawiki.org/wiki/UploadWizard) which...
- guides the users through the uploading process
- makes providing copyright information a mandatory step
- offers a licensing tutorial at the upload-entrypage (which can be hidden by the user after being seen once) 
- Is an extension that is [used at wikimedia commons](https://en.wikipedia.org/wiki/Wikipedia:File_Upload_Wizard). 

I successfully installed it on another mediawiki; works fine so far and the usual upload form can be still used as a fallback. (its linked in the Upload-Wizard)

**Comment by mxa** [comment]
i like the upload wizard you referenced. Looks useful.

**Comment by jdittrich** [comment]
In my test the upload wizard seems to do very well, it eases the process for the user, and thinking about licences seems to be encouraged by its structure and the needed putting in of a name as well.

**Comment by audiocommander** [comment]
I think we should use this repo as current working version. As we all have our own LocalSettingsPrivate, I think this would be a very good workflow, as we can all test features locally.
(FYI, I also just applied the latest security fix and it's really much easier than upgrading on our Universitity's server without SSH access)

So, Jan: do you want to put the upload wizard into /exensions and add it to the LocalSettings.php or should I do it?

ps: I also removed the /latest dir, as I think it's redundant.

**Comment by jdittrich** [comment]
If you could do so, it would be nice. I can do all the customizations later on. 
I don't know how to get the stuff going,  it will probably need a database connection and the like. Is there  anything I need to know in setting it up?

**Comment by audiocommander** [comment]
I'm going to install it, it's really easy:
https://www.mediawiki.org/wiki/Extension:UploadWizard

**Comment by audiocommander** [comment]
Installed. You can take a look at LocalSettings.php for a configuration (at the end, currently from line 397 to 417)

**Comment by jdittrich** [comment]
As [several others]()https://bugzilla.wikimedia.org/show_bug.cgi?id=44682 tried to deal with the problem and as the bug to get customization fixed has low prio, I'll close the Upload Wizard bug.
