### ISSUE TITLE
add custom licence to upload wizard extention

### ISSUE THREAD

**Issue by jdittrich** [BauhausUniversity/MedienWiki#13]
In order to maintain the usual choice of licences we need to offer a keep-copyright-licence at the upload form. As it makes sense to use the [upload wizard](https://www.mediawiki.org/wiki/Extension:UploadWizard) I tried to add such a licence to it. I was not sucessfull in adding one: I inserted a

```
'myown' => array('msg' => 'mwe-upwiz-license-myown')
```

in the UploadWizard.config.php

and added a matching

```
'mwe-upwiz-license-myown' => 'my custom licence text',
```

to the _$messages['en'] = array(…_ in the UploadWizard.i18n.php.

However, I got only to choose _[mwe-upwiz-license-stillown]_ as an option in the GUI, when selecting a licence in the interface, which is simply the variable-name surrounded by [ ]. I already checked the PHP error log and the javascript console but both did not point me in the right direction to solve the problem. 

Could somebody more proficient at mediawiki and/or php have a look?
(the source is actually well commented)

**Comment by audiocommander** [comment]
I can take a look at the source as soon as we are going to activate this extension in the current repository (it's easier to have a look at actual code than discussing it abstractly).

However, I tend to not allow the upload of any copyrighted material, even if it's from the uploader itself. I would like to force users to either use a creative commons license or to not upload anything at all. The nature of a wiki is: someone might use this image on another page and (in theory) this might already be a violation of the German Urheberrecht in terms of a properly licensed usage (vgl. uneingeschränktes/eingeschränktes und ausschließliches/nicht ausschließliches Nutzungsrecht).

I really don't see why anyone wouldn't want to use a Creative Commons by-nd-nc license. The only reason I can think of is the option to sue somebody (^_^)

**Comment by jdittrich** [comment]
could you have a look at the issue? I don't get it running. The [how-to](https://github.com/BauhausUniversity/MedienWiki/wiki/UploadWizard) so far  (scroll down).

**Comment by audiocommander** [comment]
I couldn't get it to work either, I have to read through the code and sleep over it to understand it better.
However, I have learned three things:
1. I needed to move the LocalSettingsPrivate back to the top as we need that $wpScriptPath there. Nevertheless, I moved the $wgMainCacheType into the privateSettings, so that should work for you.
2. There seems to be a really nice PHP -> JavaScript parser; that means you should look into the JS console (Firebug or Webkit) to see potential problems with the license array. That looks really interesting.
3. Documentation is sparse, so it really helps to just look in the code: UploadWizard.config.php, lines 149ff. I'm not sure in what way custom licenses should work - if they override the default licenses (so if we need to override the licenses array) or if they are supposed to extend the current option (add it to the licenses array). I tried and failed with the second option. Also there's a "custom license" title in this array as well. And I totally didn't get where the msg info is coming from. So while I could add a license to show the msg title, I couldn't figure out how to create a MW-page to show the actual message.

**Comment by jdittrich** [comment]
to 3) you create the MW-Page by (being an Admin) and creating a page like _http://localhost/myWikiFolder/index.php/MediaWiki:Mwe-upwiz-license-cc-by-sa-3.0_ (that one already exists). I e.g. did so with _http://localhost/myWikiFolder/index.php/MediaWiki:Mwe-upwiz-license-myown_

to 3) I was able to make it make some changes when I put the changes directly in the config file. That is very bad practice™. But maybe you know what the most equivalent thing you can do from the local config. (noob guess: php array merge?)  

to 2) OIC, I thought this is only JS. Though as I did not change anything regarding Javascript code I already assumed that the messages here rather point to some php trouble I caused. ;-)

Maybe the people on the [Mediawiki IRC](https://www.mediawiki.org/wiki/MediaWiki_on_IRC) are willing to help?

**Comment by audiocommander** [comment]
I tend to replace the default options with custom options... as I think in our case CC-BY-NC-ND would be the preferred default option.
Though, I really (still) have no idea where the text comes from, as I was not able to create a MW-Page. (I mean, I could create this page, but it wasn't shown, instead all I saw was [mwe-upwiz-license-cc-by-sa-3.0-msg] and ...-description]. I also tried different Namespaces. But then again, my time is currently a bit limited an I might find out more if I can have a more relaxed look.

**Comment by jdittrich** [comment]
hmm. I found this snippet from the source interesting:

``` php

// 'licenses' is a list of licenses you could possibly use elsewhere, for instance in
// licensesOwnWork or licensesThirdParty.
// It just describes what licenses go with what wikitext, and how to display them in
// a menu of license choices. There probably isn't any reason to delete any entry here.
// Under normal circumstances, the license name is the name of the wikitext template to insert.
// For those that aren't, there is a "templates" property.
'licenses' => array(…
  //loads of licence stuff goes here
  //ends again
…)

// Custom wikitext must have at least one template that is a descendant of this category
'licenseCategory' => 'License tags',

// When checking custom wikitext licenses, parse these templates as "filters";
// their arguments look like strings but they are really templates
'licenseTagFilters' => array( 'self' ),
```

If you have time again, maybe it helps...

**Comment by jdittrich** [comment]
This does not look good: 
https://bugzilla.wikimedia.org/show_bug.cgi?id=44682
_>"Well this will be a lot of work, unfortunately UploadWizard isn't made so
generic that it can be used outside of WMF wikis."_
So… possibly @gabriel-rausch would like to code an WikiEditor extension with me.

**Comment by jdittrich** [comment]
As I did not continue to work on this, and the but does not encourage doing otherwise, I'll close this.
