### ISSUE TITLE
Usability: Editing/Images – Lightbox showing insert and recent edits

### ISSUE THREAD

**Issue by jdittrich** [BauhausUniversity/MedienWiki#14]
It is a common practice to first upload media in order to link it than in an article. It is tedious for users to need to remember the wiki-filename of an image they want to insert. A possible solution would be a custom function of the [WikiEditor](https://www.mediawiki.org/wiki/Extension:WikiEditor) made by an [CommonJS](https://www.mediawiki.org/wiki/Manual:Interface/JavaScript) code which implements additional editor functionality. (The [editor is made to work that way](https://www.mediawiki.org/wiki/Extension:WikiEditor/Toolbar_customization), it's not a custom hack)

The Function does the following: It opens a lightbox for inserting an image using the fields "caption" and "Filename" (Which, concatenated  as [[filename|caption] make a image link)

In addition the latest uploads of the user are retrieved via the [API](https://www.mediawiki.org/wiki/API:Main_page). This is done by listing [Recent Changes](https://www.mediawiki.org/wiki/API:Recentchanges) and constraining the to Files and to the current user, whose name can be retrived by using [mw.config.wgUserName](https://www.mediawiki.org/wiki/Manual:Interface/JavaScript). 
The file Names of the last ~2 Uploads are displayed and can be used in the field by a click on "use this" .

![insertionwiz](https://f.cloud.github.com/assets/3416487/455278/a20d05c0-b34d-11e2-95db-5fc3d6b52c35.png)
- [x] Working Prototype
- [ ] Fixed bug #18 (Dialog Boxes only work sometimes) 
- [x] Fixed bug #19 (Generate (small) Thumbnails (on request))
- [x] Implement Wizard steps 1 and transition to 2
- [x] Create Text for "I have not yet uploaded"
- [ ] Tests, Tests, Tests!

**Comment by jdittrich** [comment]
In reaction to all the trouble I saw with inserting images again...

Old/Original Mockup: (new scroll down or see issue)
![bildschirmfoto vom 2013-04-30 20 58 39](https://f.cloud.github.com/assets/3416487/445915/031fbd62-b1c8-11e2-8922-cde47aac1558.png)

**Comment by mxa** [comment]
be aware that common practice is not a synonym for good practice.
that's why i wrote up this tutorial:
http://www.uni-weimar.de/medien/wiki/Help:Images

a much more important UX challenge IMHO is to teach copyright issues in a way that people will understand and not just klick away warnings.

a stub/early-try to do something like this may be found here:
http://www.uni-weimar.de/medien/wiki/Sources/Images

Am 30.04.2013 um 20:59 schrieb jdittrich notifications@github.com:

**Comment by jdittrich** [comment]
> be aware that common practice is not a synonym for good practice.

Could you illustrate how this relates to the interface suggestion?

The usability of copyright is dealt with already as well, but not in this issue (its #10)

**Comment by mxa** [comment]
never mind. excuse the unrelated rant provoked by 'common practice'.
however a look at the media library in wordpress might be worth it relating to the issue. http://www.youtube.com/watch?v=VeKpGPou9n8
peace.

**Comment by jdittrich** [comment]
Two usability tests using a paper Prototype: 
- Positive Feedback
- No major Problems over all, no problems with simple one image-insert usecase

Suggestions/Ideas
- What about multiple images to insert (Could opt to a gallery)
- What about Previews? (As mediawiki already generates thumbs, we could actually use those if they are client-side accessible)

**Comment by jdittrich** [comment]
I observed a reoccurring issue in two subsequent tests: People overestimated the capabilities of the dialogue and tried to use it for uploads as well. So though for people who know that upload and image linking are two separate steps, the others may be worse of: They inserted their local path in the dialogue to upload an image, though they only ended up creating a link to a File with their local image path as filename.

**Comment by jdittrich** [comment]
New Mockup. Redesign in order to disincourage use as upload dialogue and to teach people about the possibility to link nonexistent files. I called the latter "upload link" here. The upload-link way is "not recommended for beginners", as (though being very beneficial workflow-wise) it has some contra-intuitive properties (link to not-yet-existent file) and lacks an immediate feedback of how the article looks like.  

![insertionwiz](https://f.cloud.github.com/assets/3416487/455278/a20d05c0-b34d-11e2-95db-5fc3d6b52c35.png)

**Comment by jdittrich** [comment]
https://en.wikipedia.org/w/api.php?action=query&list=allimages&ailimit=5&aisort=timestamp&aiuser=Xyphoid ...seems to be be a good way for retrieving recent images (here as example with the user "Xyphoid", for us we need to get the username and the api adress from the `mw` variable)

**Comment by audiocommander** [comment]
I fear you lost me somewhere in this topic, but if you're looking for recent images, then Special:NewFiles is the page you're looking for

**Comment by jdittrich** [comment]
no problem, the above API request works just fine at the moment. If I'd use Special: page i would need to screenscrapt this which would break soon.

**Comment by jdittrich** [comment]
fist prototype works. No thumbnails currently though.

**Comment by audiocommander** [comment]
have you set the appropriate rights to your images uploads folder? For me, thumb generation works fine, so I guess it has to do with your local test setup. By default, folders are read-only (for the webserver that is).

**Comment by jdittrich** [comment]
the thumb generation itself works fine;  the Problem itself is described in its specific issue, #19
