### ISSUE TITLE
enable API

### ISSUE THREAD

**Issue by jdittrich** [BauhausUniversity/MedienWiki#17]
In order to use autosuggest functions in the WikiEditor and similar features in future functions we might implement ourselves, we need the API to be enabled. Is there anything that opposes doing this?
(we don't need write access, just querying data)

**Comment by audiocommander** [comment]
what do you mean with "enable the API"?

**Comment by jdittrich** [comment]
just setting _$wgEnableAPI = true;_ as it is on _false_ on default.

**Comment by audiocommander** [comment]
oh, I see. I was wondering to what API you were referring to. The _MediaWiki_ API is enabled by default since long ago, no action necessary:
http://www.mediawiki.org/wiki/Manual:$wgEnableAPI
