### ISSUE TITLE
New Skin

### ISSUE THREAD

**Issue by audiocommander** [BauhausUniversity/MedienWiki#2]
Make a new 1.20/1.21/1.22 compatible skin
- [x] wireframes based on new buw design (see issue #9)
- [x] make design draft
- [x] create CSS based on Vector skin
- [ ] override skin functions where CSS editing isn't enough

**Comment by jdittrich** [comment]
current state: 
![wikifoto from 2014-04-12 21 14 29](https://cloud.githubusercontent.com/assets/3416487/2687917/b95df84a-c276-11e3-99a9-e741c693c1c9.png)

**Comment by jdittrich** [comment]
current state (on small screens, the gap between content and sidebar still exists if screen estate is not rather limited)
![bildschirmfoto vom 2014-05-09 21 04 55](https://cloud.githubusercontent.com/assets/3416487/2932223/592accfe-d7ad-11e3-8ae4-aa55cbe9bcdd.png)

**Comment by mxa** [comment]
abandoned vector for citizen
