### ISSUE TITLE
enable search suggestions

### ISSUE THREAD

**Issue by jdittrich** [BauhausUniversity/MedienWiki#21]
For improving the search experience it would be good to set [$wgEnableMWSuggest](https://www.mediawiki.org/wiki/Manual:$wgEnableMWSuggest) to `true` in order to enable search suggestions (like e.g. in the dropdown on google or, for a more direct example, see [Mediawiki](https://www.mediawiki.org/wiki/) and do a search there)

**Comment by jdittrich** [comment]
sorry, it is already enabled by default.

**Comment by audiocommander** [comment]
Besides: you don't need to open an issue for these $wgPrefs, just set this value in LocalSettings.php.
I'll know it from git-blame if there are any issues.
