### ISSUE TITLE
moving to visual editor

### ISSUE THREAD

**Issue by jdittrich** [BauhausUniversity/MedienWiki#25]
The Visual Editor is  [now default](https://www.mediawiki.org/wiki/VisualEditor) in Wikipedia which means that it is pretty stable despite being dubbed a "beta". I suggest to move along: The editor offers a seamless workflow with (conventional) wikisyntax (Using a component called ["Parsoid"](https://www.mediawiki.org/wiki/Parsoid) ). It seems to have a good usability: Text can be created and edited without recalling a specific syntax (Principle: [Recognition rather than recall](http://www.nngroup.com/articles/ten-usability-heuristics/)) and it offers a visually appealing interface. 

![bildschirmfoto vom 2013-07-01 15 32 12](https://f.cloud.github.com/assets/3416487/730395/b43dbb20-e252-11e2-911b-f8ba2f34bb4a.png)

**Comment by mxa** [comment]
done
