### ISSUE TITLE
Fresh, custom Skin needed

### ISSUE THREAD

**Issue by jdittrich** [BauhausUniversity/MedienWiki#26]
What was tried: Using the existing, [Vector](https://www.mediawiki.org/wiki/Vector)-Originating bwtest-skin using `require_once "$IP/skins/BwTest.php";` in the localsettings.php

**What worked**: No errors thrown, CSS worked
**What needs to be done**: 
- We should build this on the current 1.22-Vector; The bwtest is based on the 1.20 Vector (The 1.22 seems to include some enhancements like using LESS instead of CSS) 
- Bwtest does not include the javascript files in the skin folder, so we should check if our updated version will do. 

Note: I diffed the BwTest.php and the current Vector.php. There seem to be some changes regarding the way resources are loaded using the [resource loader](https://www.mediawiki.org/wiki/ResourceLoader)

**Comment by mxa** [comment]
I've updated the wiki to current MediaWiki stable and changed to the Citizen skin. Customizations are still ongoing/needed.
