### ISSUE TITLE
problem mit umlauten in dateinamen

### ISSUE THREAD

**Issue by mxa** [BauhausUniversity/MedienWiki#28]
Sieht so aus, als ob alle Dateien mit Umlauten kaputt sind

Beispiel: https://www.uni-weimar.de/medien/wiki/File:IOhannes_zm%C3%83%C2%B6lnig_Plug_In_Your_Cam.jpg

War vorher [[File:IOhannes zmölnig Plug In Your Cam.jpg]]

**Comment by audiocommander** [comment]
Ja, der Server wurde vom SCC aktualisiert und seitdem gibt es mehr Probleme mit Umlauten und Sonderzeichen. 
Abgesehen davon, steht ganz deutlich in den Uploads:

```
"Please name your file appropriately & don't use special characters
Don't call it "1.jpg" or "Screenshot.png"
Don't use "こんにちは.ｊｐｇ"
Don't name it ".myfile.jpg" or "My Friend's Picture.jpg""
```

Abgesehen davon, ist das Bild noch vorhanden und kann neu hochgeladen werden:
https://www.uni-weimar.de/medien/wiki/images/IOhannes_zmölnig_Plug_In_Your_Cam.jpg

**Comment by jdittrich** [comment]
Ich glaube, in meinem Upload-Wizard (geht leider erst nach Update auf 22) ist ein Überprüfungs-Script für sowas – oder es ließe sich leicht implementieren. Erfahrungsgemäß werden Hinweise in 95% der Fälle leider überlesen.

**Comment by mxa** [comment]
Windows server? Schon komisch, dass alle Sonderzeichen bei einem Server-Update in andere Zeichen umgewandelt werden...

**Comment by mxa** [comment]
Ich habe das Bild noch ein mal hochgeladen, dieses mal ohne Umlaut. Jetzt folgendes Problem: Fehler beim Erstellen des Vorschaubildes:
libgomp: Thread creation failed: Resource temporarily unavailable
https://www.uni-weimar.de/medien/wiki/File:IOhannes_zmoelnig_Plug_In_Your_Cam.jpg

**Comment by jdittrich** [comment]
hi max, das ist vermutlich issue 29: #29

**Comment by mxa** [comment]
Ist aber ein .jpg

**Comment by jdittrich** [comment]
ja. Das Problem ist da vermutlich trotzdem besser aufgehoben – das problem scheint nur nicht auf svg. beschränkt zu sein- Vermutlich ist die libmagick kaputt.

**Comment by audiocommander** [comment]
Seit dem letzten SCC Serverupdate wurden vermutlich irgendwelche PHP-Uploadgrößen- und Scriptlaufzeiten begrenzt. Wenn das Bild nicht mehr als ca. 1200 px groß ist, sollte auch die Thumbnailerstellung klappen. SVG ging noch nie, weil eine libmagick Komponente fehlt. Ich kann mich erst wieder nach meinem Urlaub darum kümmern.

**Comment by jdittrich** [comment]
@audiocommander: Ich kopiere dein statment mal zu meinem .svg-bug – wegen Doku.
