### ISSUE TITLE
Usability: Relogin leads to deleted login page

### ISSUE THREAD

**Issue by jdittrich** [BauhausUniversity/MedienWiki#7]
Reproduction: Logging out and login again immediately. 
What happends: you are directed to a page which is deleted and was titeled "login"
What should happen instead: 
1) Best way: You are redirected to the main page
2) 2nd Best: The "logout" page has a hint that you might see the page if you logged in again immediately and a link to the main page

**Comment by audiocommander** [comment]
I recommend to see if this issue happens in MediaWiki 1.20.x as well. I suppose it might have been fixed there.

**Comment by jdittrich** [comment]
fixed it is, so off it goes... tested with 1.20
